-- CREATE USER IF NOT EXISTS 'webdev'@'%' IDENTIFIED WITH mysql_native_password BY 'webdev@2024';
-- GRANT SELECT, INSERT, UPDATE, /*DELETE,*/ SHOW VIEW /*ALL PRIVILEGES*/ ON webdev.convidado TO 'webdev'@'%';
-- GRANT SELECT, INSERT, UPDATE, /*DELETE,*/ SHOW VIEW /*ALL PRIVILEGES*/ ON webdev.evento TO 'webdev'@'%';
-- FLUSH PRIVILEGES;